global:
  resolve_timeout: 1m

route:
  group_by: ['alertname','name','instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'razvananghel08@gmail.com'
        from: 'razvananghel08@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'razvananghel08@gmail.com'
        auth_identity: 'razvananghel08@gmail.com'
        auth_password: 'vuku rfhj knoh ufst'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['job', 'instance', 'name']
