package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import java.time.Instant;

//for password encryption
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

//for login
import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import ro.unibuc.prodeng.request.LoginRequest;
import java.util.Date;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    public List<UserResponse> getAllUsers() {
        return userRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    public UserResponse getUserById(String id) throws EntityNotFoundException {
        UserEntity user = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(user);
    }

    public UserEntity getUserEntityById(String id) throws EntityNotFoundException {
        return userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public UserResponse createUser(CreateUserRequest request) {
        if (userRepository.findByEmail(request.email()).isPresent()) {
            throw new IllegalArgumentException("Email already exists: " + request.email());
        }
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        String role = request.role() != null ? request.role() : "user";
        UserEntity user = new UserEntity(
                null, // ID will be generated by the repository
                request.name(),
                request.email(),
                encoder.encode(request.password()),
                role,
                Instant.now()
        );
        UserEntity saved = userRepository.save(user);
        return toResponse(saved);
    }

    public UserResponse changeName(String id, String newName) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        UserEntity updated = new UserEntity(existing.id(), newName, existing.email(), existing.password(), existing.role(), existing.createdAt());
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public void deleteUser(String id) throws EntityNotFoundException {
        if (!userRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        userRepository.deleteById(id);
        //Can't actually delete the user because of the implications. Instead, we will just change the name to [DELETED].
        // UserEntity existing = userRepository.findById(id)
        //         .orElseThrow(() -> new EntityNotFoundException(id));
        // UserEntity deleted = new UserEntity(existing.id(), "[DELETED]", existing.email(), existing.password(), existing.role(), existing.createdAt());
        // userRepository.save(deleted);
    }

    public UserResponse getUserByEmail(String email) throws EntityNotFoundException {
        UserEntity user = userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email));
        return toResponse(user);
    }

    public UserEntity getUserEntityByEmail(String email) throws EntityNotFoundException {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email));
    }

    private UserResponse toResponse(UserEntity user) {
        return new UserResponse(
                user.id(),
                user.name(),
                user.email()
        );
    }

    public String login(LoginRequest request) {
        //Look after the user with this mail
        UserEntity user = userRepository.findByEmail(request.email())
                .orElseThrow(() -> new IllegalArgumentException("Invalid email"));

        //Check the password
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        if (!encoder.matches(request.password(), user.password())) {
            throw new IllegalArgumentException("Invalid password");
        }

        //Create the token
        Algorithm algorithm = Algorithm.HMAC256("cheia-lui-mihaita-de-la-332");
        
        return JWT.create()
                .withSubject(user.email()) //Save the mail in token for future operations-identifications!!!
                .withIssuedAt(new Date())
                .withExpiresAt(new Date(System.currentTimeMillis() + 86400000)) // Expiră în 24 de ore
                .sign(algorithm);
    }
}
